### ISSUE TITLE
Feature: view as armorstand, skins system and upgrades system

### ISSUE THREAD

**Issue by Zarkness2** [Rosewood-Development/RoseMinions#1]
Add an option where apart from putting that it is big or small you can put that it is an armorstand and not just a head spinning.

Along with the previous option to change the minion texture option and write the name of the skin you want to have, to be changed by another to choose a skin that the configurator created, as the option that has the jetsminions so you can put benefits for the vips.

Add a system of upgrades where the minion will have improvements, example for the miner minion: upgrade level 1 only mines 1 block in front of him, level 2 mines 2 blocks in front of him and the peak becomes diamond, level 3 mines 3 blocks in front of him and also has the enchantments fortune 3, efficiency 5 and cooks the minerals and blocks in front of him, like the upgrades system of the jetsminions.

Add an option to link the minion to a chest to store items there.
Add an option to have a life and hunger system so they are not so ops.
Add support for the itemsadder to custom texture both the inventories and the minion.
Add a limit of minions per user according to the permissions they have.
Add the possibility that the miners minion the option of which way to mine appears in the main menu of the minion.
Add an option to customize all the menus.
add an option to hide in the menus certain modules, like for example the itempickup module because when I click on it, it opens an empty menu.

Then obviously each option would be nice to need a permission, so you can put an option for vips or for all and sorry for mentioning so much another plugin but it is the only way I can think of to understand how the system is.

I have been testing the breaker module and it only breaks soil blocks and grass blocks.
I was also testing the experience module, I gave me 50 levels and I tried to give all of them and I only get 750 experience points and then it doesn't let me give more experience, then if I put it with the miner or slayer module it doesn't collect the xp either from the mobs or from the ores that I put in front of it.

**Comment by Oribuin** [comment]
Thank you for your suggestions, a good amount of these we do have planned to add already. I do also appreciate the bug reports and I'll look into them.

I will note the plugin is in very very very early stages of development and we're currently still trying to get a stable ground on how it will operate, it's pretty low on our priorities for active development due to a lack of free time split amongst the devs.
